# -*- coding: utf-8 -*-
"""дз1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ubiv5RzUHQf3aSF6ObpTmqnSoPufw_1O
"""

f = round (3.456789, 4)
print(f)

a = 5
b = 2
c = ((a+b)/2)
round(c)