# -*- coding: utf-8 -*-
"""дз3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VKmJy-gCDOIgSRFa7oz930bj9F8H7B3k
"""

summ = 0
n = int(input())
while(n > 0):
    x = n % 10
    n = n//10
    summ = summ + x
print(summ)

fact = 1
n = int(input())
while (n > 1):
    fact = fact * n
    n = n - 1
print(fact)

n = int(input())
for i in range(7, n):
    if i % 7 == 0:
     print(i + 7)