# -*- coding: utf-8 -*-
"""дз2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S25WlnE3bVrXc39QxL16YmGYjfJDwyXy
"""

a = int(input())
if a % 2 == 0:
    print("Данное число четное")
else:
    print("Данное число не является четным")

a = int(input())
b = int(input())
if a > b:
     print(a)
else:
     print(b)

a = int(input())
b = int(input())
if a == b or (a % 2 == 0 and b % 2 == 0):
    print("YES")
else:
    print("NO")