# -*- coding: utf-8 -*-
"""дз4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BSSBfMy1Hs10SmCx_RonqVWBp2Y6V_pl
"""

s = "Death there mirth way the noisy merit"
print(s)
A = s.split()
print(A[::-1])

s = "In the hole in the ground there lived a hobbit"
print(s[0::2])

s = "3 5 -7 -13 43 8 0 -13 8 -1 2"
print(s)
A = s.split()
n = int(input())
for i in range(len(A)) :
      A[i] = int(A[i]) ** n
print(A)

s = str(input())
s.replace(s, 2 * s)

x = str(input())
y = str(input())
countx = len(x)
county = len(y)
print("x:", countx, "y:", county)