# -*- coding: utf-8 -*-
"""пр1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iFOlXZPry4fcoc5OVKMhrhy_Qg7s_YA7
"""

A = [2, 4, 100, 12, 9, 6]
B = [3, 5, 2, 14, 9, 24]
print(list(map(lambda x, y: x + y, A , B)))

A = [2, 4, 12, 24, 36, 34, 876, 48, 6, 13, 26, 39]
result = list(filter(lambda x: (x % 12 == 0) or (x % 13 == 0), A))
print(result)

from functools import reduce
max_number = reduce(lambda x, y: x if x > y else y, [4, 8, 2, 10, 20, 65, 5])
print(max_number)